source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Vigilant_Example', :exclusive => true do
  pod 'Vigilant', :path => '../'
end

target 'Vigilant_Tests', :exclusive => true do
  pod 'Vigilant', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end
